//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.07 at 10:02:40 AM CEST 
//


package https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aduanas.es.aeat.adds.jdit.g4.ws.g4auxdataelementsv1;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for DeclarationTd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeclarationTd">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LRN" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}LRN_Td"/>
 *         &lt;element name="SupervisingCustomsOffice" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}CustomsOfficeTd"/>
 *         &lt;element name="EstimatedDateAndTimeOfArrival" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}DateTime19"/>
 *         &lt;element name="Declarant" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}DeclarantTd"/>
 *         &lt;element name="Representative" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}RepresentativeTd" minOccurs="0"/>
 *         &lt;element name="SpecificCircumstance" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}SpecificCircumstanceTd" minOccurs="0"/>
 *         &lt;element name="Authorisation" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}AuthorisationTd" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="HolderTransitProcedure" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}DeclarantTd" minOccurs="0"/>
 *         &lt;element name="DepartureCustomsOffice" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}CustomsOfficeTd" minOccurs="0"/>
 *         &lt;element name="MC_MasterConsignment" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}MasterConsignmentTd"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeclarationTd", propOrder = {
    "lrn",
    "supervisingCustomsOffice",
    "estimatedDateAndTimeOfArrival",
    "declarant",
    "representative",
    "specificCircumstance",
    "authorisation",
    "holderTransitProcedure",
    "departureCustomsOffice",
    "mcMasterConsignment"
})
public class DeclarationTd {

    @XmlElement(name = "LRN", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String lrn;
    @XmlElement(name = "SupervisingCustomsOffice", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String supervisingCustomsOffice;
    @XmlElement(name = "EstimatedDateAndTimeOfArrival", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date estimatedDateAndTimeOfArrival;
    @XmlElement(name = "Declarant", required = true)
    protected DeclarantTd declarant;
    @XmlElement(name = "Representative")
    protected RepresentativeTd representative;
    @XmlElement(name = "SpecificCircumstance")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String specificCircumstance;
    @XmlElement(name = "Authorisation")
    protected List<AuthorisationTd> authorisation;
    @XmlElement(name = "HolderTransitProcedure")
    protected DeclarantTd holderTransitProcedure;
    @XmlElement(name = "DepartureCustomsOffice")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String departureCustomsOffice;
    @XmlElement(name = "MC_MasterConsignment", required = true)
    protected MasterConsignmentTd mcMasterConsignment;

    /**
     * Gets the value of the lrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLRN() {
        return lrn;
    }

    /**
     * Sets the value of the lrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLRN(String value) {
        this.lrn = value;
    }

    /**
     * Gets the value of the supervisingCustomsOffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisingCustomsOffice() {
        return supervisingCustomsOffice;
    }

    /**
     * Sets the value of the supervisingCustomsOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisingCustomsOffice(String value) {
        this.supervisingCustomsOffice = value;
    }

    /**
     * Gets the value of the estimatedDateAndTimeOfArrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getEstimatedDateAndTimeOfArrival() {
        return estimatedDateAndTimeOfArrival;
    }

    /**
     * Sets the value of the estimatedDateAndTimeOfArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstimatedDateAndTimeOfArrival(Date value) {
        this.estimatedDateAndTimeOfArrival = value;
    }

    /**
     * Gets the value of the declarant property.
     * 
     * @return
     *     possible object is
     *     {@link DeclarantTd }
     *     
     */
    public DeclarantTd getDeclarant() {
        return declarant;
    }

    /**
     * Sets the value of the declarant property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclarantTd }
     *     
     */
    public void setDeclarant(DeclarantTd value) {
        this.declarant = value;
    }

    /**
     * Gets the value of the representative property.
     * 
     * @return
     *     possible object is
     *     {@link RepresentativeTd }
     *     
     */
    public RepresentativeTd getRepresentative() {
        return representative;
    }

    /**
     * Sets the value of the representative property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepresentativeTd }
     *     
     */
    public void setRepresentative(RepresentativeTd value) {
        this.representative = value;
    }

    /**
     * Gets the value of the specificCircumstance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificCircumstance() {
        return specificCircumstance;
    }

    /**
     * Sets the value of the specificCircumstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificCircumstance(String value) {
        this.specificCircumstance = value;
    }

    /**
     * Gets the value of the authorisation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorisation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorisation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorisationTd }
     * 
     * 
     */
    public List<AuthorisationTd> getAuthorisation() {
        if (authorisation == null) {
            authorisation = new ArrayList<AuthorisationTd>();
        }
        return this.authorisation;
    }

    /**
     * Gets the value of the holderTransitProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link DeclarantTd }
     *     
     */
    public DeclarantTd getHolderTransitProcedure() {
        return holderTransitProcedure;
    }

    /**
     * Sets the value of the holderTransitProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclarantTd }
     *     
     */
    public void setHolderTransitProcedure(DeclarantTd value) {
        this.holderTransitProcedure = value;
    }

    /**
     * Gets the value of the departureCustomsOffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureCustomsOffice() {
        return departureCustomsOffice;
    }

    /**
     * Sets the value of the departureCustomsOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureCustomsOffice(String value) {
        this.departureCustomsOffice = value;
    }

    /**
     * Gets the value of the mcMasterConsignment property.
     * 
     * @return
     *     possible object is
     *     {@link MasterConsignmentTd }
     *     
     */
    public MasterConsignmentTd getMCMasterConsignment() {
        return mcMasterConsignment;
    }

    /**
     * Sets the value of the mcMasterConsignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterConsignmentTd }
     *     
     */
    public void setMCMasterConsignment(MasterConsignmentTd value) {
        this.mcMasterConsignment = value;
    }

}
