//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.01 at 01:12:17 PM CEST 
//


package https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aduanas.es.aeat.adds.jdit.g4.ws.g4auxdataelementsv1;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemTd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemTd">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GoodsItemNumber" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}GoodsItemNumberTd"/>
 *         &lt;element name="Commodity" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}CommodityTd"/>
 *         &lt;element name="GrossMass" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}GrossMassTd"/>
 *         &lt;element name="Packaging" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}PackagingTd" maxOccurs="99"/>
 *         &lt;element name="TransportEquipment" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}TransportEquipmentTd" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="PreviousDocument" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}PreviousDocumentTd" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="SupportingDocument" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}SupportingDocumentTd" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="AdditionalReference" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}AdditionalReferenceTd" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="AdditionalInformation" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}AdditionalInformationTd" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="AdditionalSupplyChainActor" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}AdditionalSupplyChainActorTd" maxOccurs="99" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemTd", propOrder = {
    "goodsItemNumber",
    "commodity",
    "grossMass",
    "packaging",
    "transportEquipment",
    "previousDocument",
    "supportingDocument",
    "additionalReference",
    "additionalInformation",
    "additionalSupplyChainActor"
})
public class ItemTd {

    @XmlElement(name = "GoodsItemNumber", required = true)
    protected BigInteger goodsItemNumber;
    @XmlElement(name = "Commodity", required = true)
    protected CommodityTd commodity;
    @XmlElement(name = "GrossMass", required = true)
    protected BigDecimal grossMass;
    @XmlElement(name = "Packaging", required = true)
    protected List<PackagingTd> packaging;
    @XmlElement(name = "TransportEquipment")
    protected List<TransportEquipmentTd> transportEquipment;
    @XmlElement(name = "PreviousDocument")
    protected List<PreviousDocumentTd> previousDocument;
    @XmlElement(name = "SupportingDocument")
    protected List<SupportingDocumentTd> supportingDocument;
    @XmlElement(name = "AdditionalReference")
    protected List<AdditionalReferenceTd> additionalReference;
    @XmlElement(name = "AdditionalInformation")
    protected List<AdditionalInformationTd> additionalInformation;
    @XmlElement(name = "AdditionalSupplyChainActor")
    protected List<AdditionalSupplyChainActorTd> additionalSupplyChainActor;

    /**
     * Gets the value of the goodsItemNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGoodsItemNumber() {
        return goodsItemNumber;
    }

    /**
     * Sets the value of the goodsItemNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGoodsItemNumber(BigInteger value) {
        this.goodsItemNumber = value;
    }

    /**
     * Gets the value of the commodity property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityTd }
     *     
     */
    public CommodityTd getCommodity() {
        return commodity;
    }

    /**
     * Sets the value of the commodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityTd }
     *     
     */
    public void setCommodity(CommodityTd value) {
        this.commodity = value;
    }

    /**
     * Gets the value of the grossMass property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossMass() {
        return grossMass;
    }

    /**
     * Sets the value of the grossMass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossMass(BigDecimal value) {
        this.grossMass = value;
    }

    /**
     * Gets the value of the packaging property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packaging property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackaging().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackagingTd }
     * 
     * 
     */
    public List<PackagingTd> getPackaging() {
        if (packaging == null) {
            packaging = new ArrayList<PackagingTd>();
        }
        return this.packaging;
    }

    /**
     * Gets the value of the transportEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportEquipmentTd }
     * 
     * 
     */
    public List<TransportEquipmentTd> getTransportEquipment() {
        if (transportEquipment == null) {
            transportEquipment = new ArrayList<TransportEquipmentTd>();
        }
        return this.transportEquipment;
    }

    /**
     * Gets the value of the previousDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the previousDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreviousDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PreviousDocumentTd }
     * 
     * 
     */
    public List<PreviousDocumentTd> getPreviousDocument() {
        if (previousDocument == null) {
            previousDocument = new ArrayList<PreviousDocumentTd>();
        }
        return this.previousDocument;
    }

    /**
     * Gets the value of the supportingDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportingDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportingDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportingDocumentTd }
     * 
     * 
     */
    public List<SupportingDocumentTd> getSupportingDocument() {
        if (supportingDocument == null) {
            supportingDocument = new ArrayList<SupportingDocumentTd>();
        }
        return this.supportingDocument;
    }

    /**
     * Gets the value of the additionalReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalReferenceTd }
     * 
     * 
     */
    public List<AdditionalReferenceTd> getAdditionalReference() {
        if (additionalReference == null) {
            additionalReference = new ArrayList<AdditionalReferenceTd>();
        }
        return this.additionalReference;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalInformationTd }
     * 
     * 
     */
    public List<AdditionalInformationTd> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<AdditionalInformationTd>();
        }
        return this.additionalInformation;
    }

    /**
     * Gets the value of the additionalSupplyChainActor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalSupplyChainActor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalSupplyChainActor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalSupplyChainActorTd }
     * 
     * 
     */
    public List<AdditionalSupplyChainActorTd> getAdditionalSupplyChainActor() {
        if (additionalSupplyChainActor == null) {
            additionalSupplyChainActor = new ArrayList<AdditionalSupplyChainActorTd>();
        }
        return this.additionalSupplyChainActor;
    }

}
