//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.01 at 01:12:17 PM CEST 
//


package https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aduanas.es.aeat.adds.jdit.g4.ws.g4auxdataelementsv1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MasterConsignmentTd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MasterConsignmentTd">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransportDocument" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}TransportDocumentTd" minOccurs="0"/>
 *         &lt;element name="UCR" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}UCR_Td" minOccurs="0"/>
 *         &lt;element name="ArrivalTransportMeans" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}TransportMeansTd" minOccurs="0"/>
 *         &lt;element name="PlaceOfLoading" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}PlaceTd" minOccurs="0"/>
 *         &lt;element name="PlaceOfUnloading" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}PlaceTd" minOccurs="0"/>
 *         &lt;element name="LocationOfGoods" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}LocationOfGoodsTd" minOccurs="0"/>
 *         &lt;element name="Warehouse" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}WarehouseTd" minOccurs="0"/>
 *         &lt;element name="Consignor" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}ActorTd" minOccurs="0"/>
 *         &lt;element name="Consignee" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}ActorTd" minOccurs="0"/>
 *         &lt;element name="NotifyParty" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}ActorTd" minOccurs="0"/>
 *         &lt;element name="TotalGrossMass" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}GrossMassTd" minOccurs="0"/>
 *         &lt;element name="TransportEquipment" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}TransportEquipmentTd" maxOccurs="9999" minOccurs="0"/>
 *         &lt;element name="Receptacle" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}ReceptacleTd" maxOccurs="9999" minOccurs="0"/>
 *         &lt;element name="PreviousDocument" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}PreviousDocumentTd" maxOccurs="9999" minOccurs="0"/>
 *         &lt;element name="SupportingDocument" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}SupportingDocumentTd" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="AdditionalInformation" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}AdditionalInformationTd" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="AdditionalSupplyChainActor" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}AdditionalSupplyChainActorTd" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="DeclarationType" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}DeclarationTypeTd" minOccurs="0"/>
 *         &lt;element name="DestinatationCountry" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}CountryTd" minOccurs="0"/>
 *         &lt;element name="MI_MasterConsignment_Item" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}ItemTd" maxOccurs="9999" minOccurs="0"/>
 *         &lt;element name="HC_HouseConsignment" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}HouseConsignmentTd" maxOccurs="99999" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MasterConsignmentTd", propOrder = {
    "transportDocument",
    "ucr",
    "arrivalTransportMeans",
    "placeOfLoading",
    "placeOfUnloading",
    "locationOfGoods",
    "warehouse",
    "consignor",
    "consignee",
    "notifyParty",
    "totalGrossMass",
    "transportEquipment",
    "receptacle",
    "previousDocument",
    "supportingDocument",
    "additionalInformation",
    "additionalSupplyChainActor",
    "declarationType",
    "destinatationCountry",
    "miMasterConsignmentItem",
    "hcHouseConsignment"
})
public class MasterConsignmentTd {

    @XmlElement(name = "TransportDocument")
    protected TransportDocumentTd transportDocument;
    @XmlElement(name = "UCR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String ucr;
    @XmlElement(name = "ArrivalTransportMeans")
    protected TransportMeansTd arrivalTransportMeans;
    @XmlElement(name = "PlaceOfLoading")
    protected PlaceTd placeOfLoading;
    @XmlElement(name = "PlaceOfUnloading")
    protected PlaceTd placeOfUnloading;
    @XmlElement(name = "LocationOfGoods")
    protected LocationOfGoodsTd locationOfGoods;
    @XmlElement(name = "Warehouse")
    protected WarehouseTd warehouse;
    @XmlElement(name = "Consignor")
    protected ActorTd consignor;
    @XmlElement(name = "Consignee")
    protected ActorTd consignee;
    @XmlElement(name = "NotifyParty")
    protected ActorTd notifyParty;
    @XmlElement(name = "TotalGrossMass")
    protected BigDecimal totalGrossMass;
    @XmlElement(name = "TransportEquipment")
    protected List<TransportEquipmentTd> transportEquipment;
    @XmlElement(name = "Receptacle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> receptacle;
    @XmlElement(name = "PreviousDocument")
    protected List<PreviousDocumentTd> previousDocument;
    @XmlElement(name = "SupportingDocument")
    protected List<SupportingDocumentTd> supportingDocument;
    @XmlElement(name = "AdditionalInformation")
    protected List<AdditionalInformationTd> additionalInformation;
    @XmlElement(name = "AdditionalSupplyChainActor")
    protected List<AdditionalSupplyChainActorTd> additionalSupplyChainActor;
    @XmlElement(name = "DeclarationType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String declarationType;
    @XmlElement(name = "DestinatationCountry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String destinatationCountry;
    @XmlElement(name = "MI_MasterConsignment_Item")
    protected List<ItemTd> miMasterConsignmentItem;
    @XmlElement(name = "HC_HouseConsignment")
    protected List<HouseConsignmentTd> hcHouseConsignment;

    /**
     * Gets the value of the transportDocument property.
     * 
     * @return
     *     possible object is
     *     {@link TransportDocumentTd }
     *     
     */
    public TransportDocumentTd getTransportDocument() {
        return transportDocument;
    }

    /**
     * Sets the value of the transportDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportDocumentTd }
     *     
     */
    public void setTransportDocument(TransportDocumentTd value) {
        this.transportDocument = value;
    }

    /**
     * Gets the value of the ucr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCR() {
        return ucr;
    }

    /**
     * Sets the value of the ucr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCR(String value) {
        this.ucr = value;
    }

    /**
     * Gets the value of the arrivalTransportMeans property.
     * 
     * @return
     *     possible object is
     *     {@link TransportMeansTd }
     *     
     */
    public TransportMeansTd getArrivalTransportMeans() {
        return arrivalTransportMeans;
    }

    /**
     * Sets the value of the arrivalTransportMeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportMeansTd }
     *     
     */
    public void setArrivalTransportMeans(TransportMeansTd value) {
        this.arrivalTransportMeans = value;
    }

    /**
     * Gets the value of the placeOfLoading property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceTd }
     *     
     */
    public PlaceTd getPlaceOfLoading() {
        return placeOfLoading;
    }

    /**
     * Sets the value of the placeOfLoading property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceTd }
     *     
     */
    public void setPlaceOfLoading(PlaceTd value) {
        this.placeOfLoading = value;
    }

    /**
     * Gets the value of the placeOfUnloading property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceTd }
     *     
     */
    public PlaceTd getPlaceOfUnloading() {
        return placeOfUnloading;
    }

    /**
     * Sets the value of the placeOfUnloading property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceTd }
     *     
     */
    public void setPlaceOfUnloading(PlaceTd value) {
        this.placeOfUnloading = value;
    }

    /**
     * Gets the value of the locationOfGoods property.
     * 
     * @return
     *     possible object is
     *     {@link LocationOfGoodsTd }
     *     
     */
    public LocationOfGoodsTd getLocationOfGoods() {
        return locationOfGoods;
    }

    /**
     * Sets the value of the locationOfGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationOfGoodsTd }
     *     
     */
    public void setLocationOfGoods(LocationOfGoodsTd value) {
        this.locationOfGoods = value;
    }

    /**
     * Gets the value of the warehouse property.
     * 
     * @return
     *     possible object is
     *     {@link WarehouseTd }
     *     
     */
    public WarehouseTd getWarehouse() {
        return warehouse;
    }

    /**
     * Sets the value of the warehouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarehouseTd }
     *     
     */
    public void setWarehouse(WarehouseTd value) {
        this.warehouse = value;
    }

    /**
     * Gets the value of the consignor property.
     * 
     * @return
     *     possible object is
     *     {@link ActorTd }
     *     
     */
    public ActorTd getConsignor() {
        return consignor;
    }

    /**
     * Sets the value of the consignor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActorTd }
     *     
     */
    public void setConsignor(ActorTd value) {
        this.consignor = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link ActorTd }
     *     
     */
    public ActorTd getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActorTd }
     *     
     */
    public void setConsignee(ActorTd value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the notifyParty property.
     * 
     * @return
     *     possible object is
     *     {@link ActorTd }
     *     
     */
    public ActorTd getNotifyParty() {
        return notifyParty;
    }

    /**
     * Sets the value of the notifyParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActorTd }
     *     
     */
    public void setNotifyParty(ActorTd value) {
        this.notifyParty = value;
    }

    /**
     * Gets the value of the totalGrossMass property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalGrossMass() {
        return totalGrossMass;
    }

    /**
     * Sets the value of the totalGrossMass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalGrossMass(BigDecimal value) {
        this.totalGrossMass = value;
    }

    /**
     * Gets the value of the transportEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportEquipmentTd }
     * 
     * 
     */
    public List<TransportEquipmentTd> getTransportEquipment() {
        if (transportEquipment == null) {
            transportEquipment = new ArrayList<TransportEquipmentTd>();
        }
        return this.transportEquipment;
    }

    /**
     * Gets the value of the receptacle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the receptacle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReceptacle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getReceptacle() {
        if (receptacle == null) {
            receptacle = new ArrayList<String>();
        }
        return this.receptacle;
    }

    /**
     * Gets the value of the previousDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the previousDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreviousDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PreviousDocumentTd }
     * 
     * 
     */
    public List<PreviousDocumentTd> getPreviousDocument() {
        if (previousDocument == null) {
            previousDocument = new ArrayList<PreviousDocumentTd>();
        }
        return this.previousDocument;
    }

    /**
     * Gets the value of the supportingDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportingDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportingDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportingDocumentTd }
     * 
     * 
     */
    public List<SupportingDocumentTd> getSupportingDocument() {
        if (supportingDocument == null) {
            supportingDocument = new ArrayList<SupportingDocumentTd>();
        }
        return this.supportingDocument;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalInformationTd }
     * 
     * 
     */
    public List<AdditionalInformationTd> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<AdditionalInformationTd>();
        }
        return this.additionalInformation;
    }

    /**
     * Gets the value of the additionalSupplyChainActor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalSupplyChainActor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalSupplyChainActor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalSupplyChainActorTd }
     * 
     * 
     */
    public List<AdditionalSupplyChainActorTd> getAdditionalSupplyChainActor() {
        if (additionalSupplyChainActor == null) {
            additionalSupplyChainActor = new ArrayList<AdditionalSupplyChainActorTd>();
        }
        return this.additionalSupplyChainActor;
    }

    /**
     * Gets the value of the declarationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeclarationType() {
        return declarationType;
    }

    /**
     * Sets the value of the declarationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeclarationType(String value) {
        this.declarationType = value;
    }

    /**
     * Gets the value of the destinatationCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinatationCountry() {
        return destinatationCountry;
    }

    /**
     * Sets the value of the destinatationCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinatationCountry(String value) {
        this.destinatationCountry = value;
    }

    /**
     * Gets the value of the miMasterConsignmentItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miMasterConsignmentItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMIMasterConsignmentItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemTd }
     * 
     * 
     */
    public List<ItemTd> getMIMasterConsignmentItem() {
        if (miMasterConsignmentItem == null) {
            miMasterConsignmentItem = new ArrayList<ItemTd>();
        }
        return this.miMasterConsignmentItem;
    }

    /**
     * Gets the value of the hcHouseConsignment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hcHouseConsignment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHCHouseConsignment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HouseConsignmentTd }
     * 
     * 
     */
    public List<HouseConsignmentTd> getHCHouseConsignment() {
        if (hcHouseConsignment == null) {
            hcHouseConsignment = new ArrayList<HouseConsignmentTd>();
        }
        return this.hcHouseConsignment;
    }

}
