//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.07 at 10:02:40 AM CEST 
//


package https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aduanas.es.aeat.adds.jdit.g4.ws.g4auxdataelementsv1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MasterConsignmentSimpTd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MasterConsignmentSimpTd">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransDocRefNum" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}DocRefLongTd"/>
 *         &lt;choice>
 *           &lt;element name="MI_Simp" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}ItemSimpTd" maxOccurs="9999" minOccurs="0"/>
 *           &lt;element name="HC_Simp" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aduanas/es/aeat/adds/jdit/g4/ws/G4AuxDataElementsV1.xsd}HouseConsignmentSimpTd" maxOccurs="99999"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MasterConsignmentSimpTd", propOrder = {
    "transDocRefNum",
    "miSimp",
    "hcSimp"
})
public class MasterConsignmentSimpTd {

    @XmlElement(name = "TransDocRefNum", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String transDocRefNum;
    @XmlElement(name = "MI_Simp")
    protected List<ItemSimpTd> miSimp;
    @XmlElement(name = "HC_Simp")
    protected List<HouseConsignmentSimpTd> hcSimp;

    /**
     * Gets the value of the transDocRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransDocRefNum() {
        return transDocRefNum;
    }

    /**
     * Sets the value of the transDocRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransDocRefNum(String value) {
        this.transDocRefNum = value;
    }

    /**
     * Gets the value of the miSimp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miSimp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMISimp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemSimpTd }
     * 
     * 
     */
    public List<ItemSimpTd> getMISimp() {
        if (miSimp == null) {
            miSimp = new ArrayList<ItemSimpTd>();
        }
        return this.miSimp;
    }

    /**
     * Gets the value of the hcSimp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hcSimp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHCSimp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HouseConsignmentSimpTd }
     * 
     * 
     */
    public List<HouseConsignmentSimpTd> getHCSimp() {
        if (hcSimp == null) {
            hcSimp = new ArrayList<HouseConsignmentSimpTd>();
        }
        return this.hcSimp;
    }

}
