//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.01 at 01:12:17 PM CEST 
//


package https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aduanas.es.aeat.adds.jdit.g4.ws.g4auxdataelementsv1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aduanas.es.aeat.adds.jdit.g4.ws.g4auxdataelementsv1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aduanas.es.aeat.adds.jdit.g4.ws.g4auxdataelementsv1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocationOfGoodsTd }
     * 
     */
    public LocationOfGoodsTd createLocationOfGoodsTd() {
        return new LocationOfGoodsTd();
    }

    /**
     * Create an instance of {@link LocationOfGoodsTd.LocCoded }
     * 
     */
    public LocationOfGoodsTd.LocCoded createLocationOfGoodsTdLocCoded() {
        return new LocationOfGoodsTd.LocCoded();
    }

    /**
     * Create an instance of {@link MessageTd }
     * 
     */
    public MessageTd createMessageTd() {
        return new MessageTd();
    }

    /**
     * Create an instance of {@link DeclarationTd }
     * 
     */
    public DeclarationTd createDeclarationTd() {
        return new DeclarationTd();
    }

    /**
     * Create an instance of {@link AdditionalInformationTd }
     * 
     */
    public AdditionalInformationTd createAdditionalInformationTd() {
        return new AdditionalInformationTd();
    }

    /**
     * Create an instance of {@link MasterConsignmentSimpTd }
     * 
     */
    public MasterConsignmentSimpTd createMasterConsignmentSimpTd() {
        return new MasterConsignmentSimpTd();
    }

    /**
     * Create an instance of {@link WarehouseTd }
     * 
     */
    public WarehouseTd createWarehouseTd() {
        return new WarehouseTd();
    }

    /**
     * Create an instance of {@link HouseConsignmentTd }
     * 
     */
    public HouseConsignmentTd createHouseConsignmentTd() {
        return new HouseConsignmentTd();
    }

    /**
     * Create an instance of {@link RepresentativeTd }
     * 
     */
    public RepresentativeTd createRepresentativeTd() {
        return new RepresentativeTd();
    }

    /**
     * Create an instance of {@link TransportDocumentTd }
     * 
     */
    public TransportDocumentTd createTransportDocumentTd() {
        return new TransportDocumentTd();
    }

    /**
     * Create an instance of {@link FullAddressTd }
     * 
     */
    public FullAddressTd createFullAddressTd() {
        return new FullAddressTd();
    }

    /**
     * Create an instance of {@link ItemTd }
     * 
     */
    public ItemTd createItemTd() {
        return new ItemTd();
    }

    /**
     * Create an instance of {@link TransportEquipmentTd }
     * 
     */
    public TransportEquipmentTd createTransportEquipmentTd() {
        return new TransportEquipmentTd();
    }

    /**
     * Create an instance of {@link HouseConsignmentSimpTd }
     * 
     */
    public HouseConsignmentSimpTd createHouseConsignmentSimpTd() {
        return new HouseConsignmentSimpTd();
    }

    /**
     * Create an instance of {@link CommunicationTd }
     * 
     */
    public CommunicationTd createCommunicationTd() {
        return new CommunicationTd();
    }

    /**
     * Create an instance of {@link ItemSimpTd }
     * 
     */
    public ItemSimpTd createItemSimpTd() {
        return new ItemSimpTd();
    }

    /**
     * Create an instance of {@link NotifATMTd }
     * 
     */
    public NotifATMTd createNotifATMTd() {
        return new NotifATMTd();
    }

    /**
     * Create an instance of {@link MasterConsignmentTd }
     * 
     */
    public MasterConsignmentTd createMasterConsignmentTd() {
        return new MasterConsignmentTd();
    }

    /**
     * Create an instance of {@link PreviousDocumentTd }
     * 
     */
    public PreviousDocumentTd createPreviousDocumentTd() {
        return new PreviousDocumentTd();
    }

    /**
     * Create an instance of {@link CommodityCodeTd }
     * 
     */
    public CommodityCodeTd createCommodityCodeTd() {
        return new CommodityCodeTd();
    }

    /**
     * Create an instance of {@link DeclarationSimpTd }
     * 
     */
    public DeclarationSimpTd createDeclarationSimpTd() {
        return new DeclarationSimpTd();
    }

    /**
     * Create an instance of {@link DeclarationSalTd }
     * 
     */
    public DeclarationSalTd createDeclarationSalTd() {
        return new DeclarationSalTd();
    }

    /**
     * Create an instance of {@link AuthorisationTd }
     * 
     */
    public AuthorisationTd createAuthorisationTd() {
        return new AuthorisationTd();
    }

    /**
     * Create an instance of {@link TransportMeansTd }
     * 
     */
    public TransportMeansTd createTransportMeansTd() {
        return new TransportMeansTd();
    }

    /**
     * Create an instance of {@link AdditionalSupplyChainActorTd }
     * 
     */
    public AdditionalSupplyChainActorTd createAdditionalSupplyChainActorTd() {
        return new AdditionalSupplyChainActorTd();
    }

    /**
     * Create an instance of {@link SupportingDocumentTd }
     * 
     */
    public SupportingDocumentTd createSupportingDocumentTd() {
        return new SupportingDocumentTd();
    }

    /**
     * Create an instance of {@link ActorTd }
     * 
     */
    public ActorTd createActorTd() {
        return new ActorTd();
    }

    /**
     * Create an instance of {@link DeclarantTd }
     * 
     */
    public DeclarantTd createDeclarantTd() {
        return new DeclarantTd();
    }

    /**
     * Create an instance of {@link AdditionalReferenceTd }
     * 
     */
    public AdditionalReferenceTd createAdditionalReferenceTd() {
        return new AdditionalReferenceTd();
    }

    /**
     * Create an instance of {@link PackagingTd }
     * 
     */
    public PackagingTd createPackagingTd() {
        return new PackagingTd();
    }

    /**
     * Create an instance of {@link CountriesRoutingTransportMeansTd }
     * 
     */
    public CountriesRoutingTransportMeansTd createCountriesRoutingTransportMeansTd() {
        return new CountriesRoutingTransportMeansTd();
    }

    /**
     * Create an instance of {@link CommodityTd }
     * 
     */
    public CommodityTd createCommodityTd() {
        return new CommodityTd();
    }

    /**
     * Create an instance of {@link PlaceTd }
     * 
     */
    public PlaceTd createPlaceTd() {
        return new PlaceTd();
    }

    /**
     * Create an instance of {@link LocationOfGoodsTd.LocAddress }
     * 
     */
    public LocationOfGoodsTd.LocAddress createLocationOfGoodsTdLocAddress() {
        return new LocationOfGoodsTd.LocAddress();
    }

    /**
     * Create an instance of {@link LocationOfGoodsTd.LocPostCodeAddress }
     * 
     */
    public LocationOfGoodsTd.LocPostCodeAddress createLocationOfGoodsTdLocPostCodeAddress() {
        return new LocationOfGoodsTd.LocPostCodeAddress();
    }

    /**
     * Create an instance of {@link LocationOfGoodsTd.LocCoded.LocCustomsOffice }
     * 
     */
    public LocationOfGoodsTd.LocCoded.LocCustomsOffice createLocationOfGoodsTdLocCodedLocCustomsOffice() {
        return new LocationOfGoodsTd.LocCoded.LocCustomsOffice();
    }

    /**
     * Create an instance of {@link LocationOfGoodsTd.LocCoded.LocGPS }
     * 
     */
    public LocationOfGoodsTd.LocCoded.LocGPS createLocationOfGoodsTdLocCodedLocGPS() {
        return new LocationOfGoodsTd.LocCoded.LocGPS();
    }

    /**
     * Create an instance of {@link LocationOfGoodsTd.LocCoded.LocEconomicOperator }
     * 
     */
    public LocationOfGoodsTd.LocCoded.LocEconomicOperator createLocationOfGoodsTdLocCodedLocEconomicOperator() {
        return new LocationOfGoodsTd.LocCoded.LocEconomicOperator();
    }

}
